### ISSUE TITLE
Please build the .xpi file for the latest release and updates

### ISSUE THREAD

**Issue by douhung1** [roosta/yank#2]
Dear Roosta,

Thank you very much for this useful firefox extension!

a few requests and suggestions:

1. I don't know how to build this extension. Please build and upload the .xpi file for the latest release and updates.

2. Now the shortcut key Ctrl+y copies URL in org-mode format. can it jump to emacs as well?

many thanks!

Hung

**Comment by roosta** [comment]
Hi, thanks for using yank :) I've been having a bit of a tooling issue and in the stages of revamping a lot of it. If you'd bear with me for a few days I'll get the latest version uploaded and signed.

As far as jumping to Emacs, its a good idea but a bit outside scope of this extension. It's meant to be used with any given editor, I'll look into it but can't promise that particular feature.

**Comment by roosta** [comment]
Ok, latest version is signed and published under [releases](https://github.com/roosta/yank/releases). The tooling issue is unrelated to the functioning of the plugin so I decided to publish the missing versions.

**Comment by douhung1** [comment]
Dear Daniel, thank you for your response and updates! I am using the
extension every day tenths of times.

One possibility is to add an option to let users to choose whether to jump
to any user-specified program. Then not only emacs users but users of any
editor will be benefited.

**Comment by roosta** [comment]
I'll give it a think, thanks for the suggestion :)
